# Generated by Django 3.2.7 on 2021-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MusicDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=500)),
                ('song_artist', models.CharField(max_length=500)),
                ('emotions', models.CharField(max_length=500)),
                ('movie_name', models.CharField(max_length=500)),
                ('song', models.FileField(default='', upload_to='musicplayer/songs')),
                ('image', models.ImageField(default='', upload_to='musicplayer/images')),
            ],
        ),
    ]
