# Generated by Django 3.2.7 on 2021-11-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_auto_20211113_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicDb',
        ),
    ]
