# Generated by Django 3.2.7 on 2021-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0004_delete_musicdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicDB',
            fields=[
                ('song_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=500)),
                ('song_artist', models.CharField(max_length=500)),
                ('emotions', models.CharField(max_length=500)),
                ('movie_name', models.CharField(max_length=500)),
                ('song_category', models.CharField(default='Genaral', max_length=500)),
                ('song', models.FileField(default='', upload_to='musicplayer/songs')),
                ('image', models.ImageField(default='', upload_to='musicplayer/images')),
            ],
        ),
    ]
