# Generated by Django 3.2.7 on 2021-11-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0005_musicdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicdb',
            name='emotions',
        ),
    ]
