# Generated by Django 3.2.7 on 2021-11-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0006_remove_musicdb_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdb',
            name='image',
            field=models.ImageField(default='media/musicplayer/images', upload_to='media/musicplayer/images'),
        ),
        migrations.AlterField(
            model_name='musicdb',
            name='song',
            field=models.FileField(default='media/musicplayer/songs', upload_to='media/musicplayer/songs'),
        ),
    ]
