# Generated by Django 3.2.7 on 2021-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0008_auto_20211114_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdb',
            name='image',
            field=models.ImageField(default='images', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='musicdb',
            name='song',
            field=models.FileField(default='songs', upload_to='songs'),
        ),
    ]
