# Generated by Django 3.2.9 on 2021-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0010_alter_musicdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdb',
            name='emojies',
            field=models.CharField(default='General', max_length=500),
        ),
        migrations.AlterField(
            model_name='musicdb',
            name='song_category',
            field=models.CharField(default='General', max_length=500),
        ),
    ]
