# Generated by Django 3.2.9 on 2021-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0013_musicdb_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdb',
            name='song_language',
            field=models.CharField(default='Hindi', max_length=500),
        ),
    ]
