# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0014_musicdb_song_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicdb',
            name='song_language',
        ),
    ]
